omap5: hwmod: Fix build breaks because of missing hwmod data.
The below errors have to be fixed using autogen data correctly.
Fixing them manually for now.

arch/arm/mach-omap2/omap_hwmod_54xx_data.c:430: error: 'omap54xx_debug_logic__l3_main_2' undeclared here (not in a function)
arch/arm/mach-omap2/omap_hwmod_54xx_data.c:1147: error: 'omap54xx_dsp__sl2' undeclared here (not in a function)
arch/arm/mach-omap2/omap_hwmod_54xx_data.c:1147: error: initializer element is not constant
arch/arm/mach-omap2/omap_hwmod_54xx_data.c:1147: error: (near initialization for 'omap54xx_dsp_masters[3]')
arch/arm/mach-omap2/omap_hwmod_54xx_data.c:2957: error: 'omap54xx_iva__sl2' undeclared here (not in a function)
arch/arm/mach-omap2/omap_hwmod_54xx_data.c:2957: error: initializer element is not constant
arch/arm/mach-omap2/omap_hwmod_54xx_data.c:2957: error: (near initialization for 'omap54xx_iva_masters[2]')

Signed-off-by: sricharan <r.sricharan@ti.com>